### ISSUE TITLE
there is no checkers

### ISSUE THREAD

**Issue by Hansausage** [superreg/checkers#1]
how do i play

please send help

**Comment by superreg** [comment]
It's not done yet; hence, no release.

**Comment by Hansausage** [comment]
Reggie Russian hackers are stealing your checkers

**Comment by superreg** [comment]
Proof?

**Comment by Hansausage** [comment]
4chan

**Comment by superreg** [comment]
Credible proof?

**Comment by superreg** [comment]
there's a checkerboard now!
